name: renovate
on:
  schedule:
    # 30分ごとに実行する
    #- cron: '0/10 * * * *'
    # 毎日18時に実行する
    #- cron: '0 9 * * *'
    # 3時間ごとに実行する
    #- cron: '0 */3 * * *'
    # 毎日AM2時に実行する
    - cron: '0 17 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.118.0
        with:
          configurationFile: tools/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
