name: renovate
on:
    schedule:
      # 60分ごとに実行する
      - cron: '0/60 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.118.0
        with:
          configurationFile: tools/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
